// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjNTQ94MmINtaDKNLhZryNH-oRAnmBS1Q',
    appId: '1:186504454637:web:d0ff487a229d7434cc87e4',
    messagingSenderId: '186504454637',
    projectId: 'my-project-368714',
    authDomain: 'my-project-368714.firebaseapp.com',
    storageBucket: 'my-project-368714.appspot.com',
    measurementId: 'G-52SV56YQE6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADly1AH22_B1og5FbH-r5HSI9sT8M0hxI',
    appId: '1:186504454637:android:934fd003dc03a0d8cc87e4',
    messagingSenderId: '186504454637',
    projectId: 'my-project-368714',
    storageBucket: 'my-project-368714.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFWUacPECgCaGS80CvdDqmM9DkTi_gGWs',
    appId: '1:186504454637:ios:6d74a58285a8f384cc87e4',
    messagingSenderId: '186504454637',
    projectId: 'my-project-368714',
    storageBucket: 'my-project-368714.appspot.com',
    iosClientId: '186504454637-ti2ofg4g13lg9vs52mpe4gn4uk3sjj2o.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFWUacPECgCaGS80CvdDqmM9DkTi_gGWs',
    appId: '1:186504454637:ios:6d74a58285a8f384cc87e4',
    messagingSenderId: '186504454637',
    projectId: 'my-project-368714',
    storageBucket: 'my-project-368714.appspot.com',
    iosClientId: '186504454637-ti2ofg4g13lg9vs52mpe4gn4uk3sjj2o.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp',
  );
}
